### ISSUE TITLE
Req 29 - Upload de arquivos em formato diferente de pdf

### ISSUE THREAD

**Issue by lizandraottmann** [BrunoSoares-LABORA/sdd-ufg#108]
O sistema permite o uploads de arquivos diferentes de pdf.
O teste foi realizado com arquivos do tipo PNG, JPG e DOCX.

![image](https://cloud.githubusercontent.com/assets/6888070/13184374/977a61c4-d722-11e5-9407-a08baa0bce91.png)

**Comment by pedroteles** [comment]
corrigido
