### ISSUE TITLE
Status do processo não é atualizado em todo sistema após alguma alteração.

### ISSUE THREAD

**Issue by lizandraottmann** [BrunoSoares-LABORA/sdd-ufg#109]
@BrunoSoares-LABORA 

Embora o status de um processo seja "Fechado"(tela 1), ao selecionar tal processo seu status é apresentado como aberto (tela 2).

![image](https://cloud.githubusercontent.com/assets/6888070/13184778/f2df1ea4-d724-11e5-815d-773b278c4dea.png)

**Comment by brunosoaresds** [comment]
@lizandraottmann 

Observe que são dois status distintos. Um é relativo a distribuição de uma determinada turma e outro é relativo ao status do processo de distribuição (que aglomera N turmas).
