### ISSUE TITLE
Req 13- Erro ao clonar processo de distribuição com o status "Aberto"

### ISSUE THREAD

**Issue by lizandraottmann** [BrunoSoares-LABORA/sdd-ufg#110]
Ao selecionar a opção "clonar" em um processo de distribuição com o status "Aberto" 
![image](https://cloud.githubusercontent.com/assets/6888070/13185323/9f328f2c-d727-11e5-945e-5192c988fac1.png)

o seguinte erro é apresentado:

![image](https://cloud.githubusercontent.com/assets/6888070/13185240/2fdd17c8-d727-11e5-9d72-0c057e269313.png)

**Comment by marlaaragao** [comment]
Creio que esse botão esteja com a ação para um método antigo/incorreto 'cloneProcess'. O método correto é 'reuseProcess()' e só pode ser chamado em processos fechados. Vou efetuar a correção assim que possível.

**Comment by pedroteles** [comment]
Um processo aberto no nosso entendimento nao deveria ser clonado, apenas processos fechados. Pode confirmar isso @marlaaragao ?

**Comment by pedroteles** [comment]
O mesmo para processos cancelados;

**Comment by marlaaragao** [comment]
Sim, somente Processos Fechados podem ser clonados. É proibida a clonagem de processos abertos ou cancelados.

**Comment by pedroteles** [comment]
@marlaaragao por favor suba a versão mais recente pois o sistema que está no servidor ainda está apresentando os erros dessa Issue.

**Comment by marlaaragao** [comment]
Já está no servidor a versão mais atual.

**Comment by pedroteles** [comment]
Problema corrigido
