### ISSUE TITLE
Problema nos campos de horário (docente e disciplina)

### ISSUE THREAD

**Issue by Tomahaawk** [BrunoSoares-LABORA/sdd-ufg#112]
Ao inserir um horário, caso o usuário insira uma letra no campo e tente modificar o valor do campo com as setinhas, o campo não é alterado

![bug campo de horario](https://cloud.githubusercontent.com/assets/12561157/13190484/80aca070-d744-11e5-965e-ea8268337c63.png)

**Comment by leticianb1** [comment]
retestado e aprovado.
