### ISSUE TITLE
Cadastro de processos - Validação de nome

### ISSUE THREAD

**Issue by leticianb1** [BrunoSoares-LABORA/sdd-ufg#120]
É possível criar processos com o campo de descrição (nome) vazio. Também é possível colocar vários processos com o mesmo nome.
![image](https://cloud.githubusercontent.com/assets/8607170/13348397/0b5098b4-dc52-11e5-8d2a-6a8f96f2f84d.png)

**Comment by weslleyma** [comment]
O campo vazio já foi corrigido. Porém não é viável para o projeto limitar o nome, pois os processos nunca são deletados, só cancelados e neste caso seria impossível criar outro com o mesmo nome.

**Comment by leticianb1** [comment]
ok.
