### ISSUE TITLE
Cadastro de processos - Opções de visualizar e editar

### ISSUE THREAD

**Issue by leticianb1** [BrunoSoares-LABORA/sdd-ufg#122]
Por algum motivo processos antigos não estão apresentando os botões de opções, como pode ser visto na imagem.

![image](https://cloud.githubusercontent.com/assets/8607170/13348924/270953ae-dc55-11e5-9c2e-a5e3bf4c65e2.png)

Como pode ser visto os processos ainda continuam abertos, porém mostrando somente a opção de visualizar (como aconteceria com um processo cancelado).

**Comment by weslleyma** [comment]
Não consegui simular este erro. Provavelmente é na base de dados e não em código, nem no console da erro.

**Comment by leticianb1** [comment]
Aparentemente era um problema na minha base de dados. Aparentemente o problema não acontece mais
