### ISSUE TITLE
Opção de fechar turma é apresentada mesmo quando a turma já esta fechada

### ISSUE THREAD

**Issue by lizandraottmann** [BrunoSoares-LABORA/sdd-ufg#126]
@BrunoSoares-LABORA 

Mesmo que uma turma já tenha sido fechada, a opção "Fechar turma" continua sendo apresentada causando confusão ao usuário. 

Na versão anterior era mostrado um link e dica indicando que a turma estava finalizada caso os arquivos da turma estivessem completos. Agora o docente que já fechou sua turma não tem essa informação sem ter que entrar em cada uma de suas turmas pra verificar os arquivos.

![image](https://cloud.githubusercontent.com/assets/6888070/13363859/817df254-dcaa-11e5-999d-662d8c6278c6.png)

**Comment by brunosoaresds** [comment]
@lizandraottmann 

O status fechado se refere apenas ao processo de distribuição desta turma está fechado, o que significa que os docentes para aquela turma foram devidamente alocados. Acredito que exista um status sencundário para essas turmas estarem deste modo finalizado fazendo com que no mínimo essa opção mude de nome para algo como (Reenviar arquivos) sei lá.
Outra coisa que pensei também é que esse envio pode inclusive estar na tela de visualização da turma, em uma outra aba, mas isto deve ser discutido com o grupo da @marlaaragao ao qual inclusive é a responsável pela implementação deste item do menu.

De qualquer forma vou fechar essa issue pois esse status "Fechado" não tem relação com essa opção, mas de fato deve ser estudado o que comentei acima.

Att.,

**Comment by lizandraottmann** [comment]
O nome desse 'status' da turma poderia ser algo como "alocada" pois "fechado" dá a entender que a turma foi finalizada e por isso esta 'fechada' (todos os arquivos enviados). 
Meu grupo, responsável pelo uploads dos arquivos havia colocado uma mensagem ao usuário o alertando sobre o envio destes, porém não se encontra mais na versão atual modificada por vc e por isso citei neste issue. Como a entrega é hoje, peço que adicione novamente o link e dica indicando que a turma estava finalizada caso os arquivos da turma estivessem completos. Se preferir posso abrir um novo issue.

Obrigada!

**Comment by brunosoaresds** [comment]
É, uma abordagem seria modificar o status desta forma ou criar esse status de envio como um status secundario, uma vez que isto não é mais relativo a distribuição da disciplina e que este envio só poderá ocorrer ao final de cada semestre. Acredito que podemos discutir isto hoje com o Juliano.

Qual mensagem era essa, consegue me enviar uma revisão ao qual existia isto? ai posso verificar e possivelmente adicionar novamente.

Att.,

**Comment by brunosoaresds** [comment]
Acredito que achei o que era. Acabei de adicionar novamente lá, verifique por favor.
