### ISSUE TITLE
CSU07 - Cadastro de docente

### ISSUE THREAD

**Issue by leticianb1** [BrunoSoares-LABORA/sdd-ufg#47]
1. Consertar o campo "Núcleo de conhecimento" pois como dica aparece CPF e o usuário não sabe o que é pra inserir
2. Os campos de datas não possuem nenhum tipo de validação (é possível colocar data de nascimento no futuro, é possível entrar na UFG antes de ter nascido, etc)
3. Não é possível colocar datas antes de 2011.
4. O ideal seria que o campo de "Carga horária" fosse um seletor, para que opções improváveis como "1" ou "123129318" não seja possível
5. Fazer validações de campos

**Comment by Tomahaawk** [comment]
1. No cadastro de docente, é possível deixar uma carga horária negativa.

**Comment by philipperuizlopes** [comment]
1. Resolvido;
2. Resolvido;
3. Resolvido;
4. Por enquanto continuará livre digitação até que se defina diferente; (Resolvido para cargas negativas);
5. Quais validações seriam essas?;

**Comment by leticianb1** [comment]
@philipperuizlopes 
1. Corrigido
2. As validações ainda não acontecem para a edição e para a funcionalidade "solicitar cadastro"
3.Ainda não foi corrigido para "solicitar cadastro"
4. Tudo bem
5. Vou reunir as validações necessárias e reportar em um documento separado.

**Comment by leticianb1** [comment]
Ok.
