### ISSUE TITLE
CSU04 - Cadastro de disciplina

### ISSUE THREAD

**Issue by leticianb1** [BrunoSoares-LABORA/sdd-ufg#48]
![image](https://cloud.githubusercontent.com/assets/8607170/12684065/daf17bde-c6a3-11e5-809a-57d492a90816.png)

Erro apresentado ao usuário na tentativa de cadastrar uma disciplina sem núcleo de conhecimento

**Comment by brunosoaresds** [comment]
Adicionada validação dos campos.
