### ISSUE TITLE
CSU13 - Cadastro do processo de distribuição

### ISSUE THREAD

**Issue by Tomahaawk** [BrunoSoares-LABORA/sdd-ufg#55]
1. Não foi possível cadastrar um processo de distribuição. Ao clicar em salvar após preencher os campos, todos foram invalidados.

![errodist](https://cloud.githubusercontent.com/assets/12561157/12691758/4c4f28ee-c6d6-11e5-863e-2d821ea5bd92.png)

**Comment by weslleyma** [comment]
Os erros reportados foram corrigidos.
