### ISSUE TITLE
Valores negativos - Campos de carga horária

### ISSUE THREAD

**Issue by Tomahaawk** [BrunoSoares-LABORA/sdd-ufg#68]
1. Todos os campos de carga horária (cadastro de docentes, cadastro de disciplinas, turmas, etc) estão aceitando valores negativos.

**Comment by brunosoaresds** [comment]
As cargas horárias relativas ao cadastro de disciplinas (turmas não possuem tal dado) foram corrigidas.

**Comment by Tomahaawk** [comment]
Cadastrar/Editar docente ainda é possível inserir valores negativos.

**Comment by leticianb1** [comment]
ok.
