### ISSUE TITLE
Cadastro de processos de distribuição

### ISSUE THREAD

**Issue by leticianb1** [BrunoSoares-LABORA/sdd-ufg#75]
1. Validar os campos de data
2. Colocar os campos "De" e "Até" lado a lado

**Comment by leticianb1** [comment]
![image](https://cloud.githubusercontent.com/assets/8607170/12861081/e33f3386-cc47-11e5-9931-a721d37e4242.png)

**Comment by leticianb1** [comment]
O botão "Fechar" da listagem apresenta o seguinte erro:

![image](https://cloud.githubusercontent.com/assets/8607170/12861113/2c1a1ef4-cc48-11e5-807d-806b9b7b1dee.png)

**Comment by weslleyma** [comment]
Já melhorei o layout como sugeriu. Sobre o erro do método close aqui não está dando erro. Verifique se sua base de dados está atualizada com a última versão, que adiciona o campo status na tabela de processos.

**Comment by leticianb1** [comment]
Há um pequeno problema com a apresentação da data. As telas de Editar, Adicionar e Listar processos apresenta formatos de datas diferentes. 

Exemplo:
Cadastrando um processo com início em "primeiro de março de 2016" e término em "doze de março de 2016" , na tela de adicionar o formato será 01/03/2016, na tela de listagem será 03/01/2016, e quando eu entrar em Editar será 1/3/16, fazendo com que quando eu salve sem nenhuma modificação, a tela de listagem comece a apresentar o valor 03/01/1916.

Se a data fosse "treze de março de 2016" na listagem ela passará a ser listada como "03/01/2017", mostrando que a conversão do mês também não está correta.

![image](https://cloud.githubusercontent.com/assets/8607170/13115592/7f75306c-d57f-11e5-9015-5c7dad979570.png)
![image](https://cloud.githubusercontent.com/assets/8607170/13115619/9d70c8d8-d57f-11e5-8589-6479b31e8d27.png)
![image](https://cloud.githubusercontent.com/assets/8607170/13115917/f3d249bc-d580-11e5-81a3-e3faba56df5f.png)

@weslleyma

**Comment by leticianb1** [comment]
O problema do botão "Fechar" foi corrigido!

**Comment by weslleyma** [comment]
Problema com as datas corrigidos.
