### ISSUE TITLE
Problemas encontrados (processos 6, 7 e perfis de usuário)

### ISSUE THREAD

**Issue by lizandraottmann** [BrunoSoares-LABORA/sdd-ufg#80]
@weslleyma 
1. Definir coordenador da distribuição
   Atualmente o cadastro de coordenador não é vinculado ao processo de distribuição. Um processo de distribuição deve possuir apenas um coordenador.
2. Definir facilitador de cada núcleo de conhecimento
   Atualmente o cadastro de facilitador não é vinculado ao processo de distribuição. Um processo de distribuição deve possuir apenas um facilitador por núcleo de conhecimento.

*Atualmente todos os usuário são docentes. Deve ser possível cadastrar usuários que não sejam docentes podendo estes serem ou não administradores (secretários, por exemplo).

**Comment by weslleyma** [comment]
Este é um problema de modelagem, não é erro na implementação.

**Comment by brunosoaresds** [comment]
De acordo com os requisitos iniciais, essa configuração era para ser global. Provavelmente ou ele não entendeu a pergunta ou como funcionaria na interface. Acredito que a forma com que está é melhor pois também não força que em cada processo seja retribuído algo que é diversas vezes repetido.

Vou fechar essa issue para confirmarmos posteriormente.
