### ISSUE TITLE
Não é possível cadastrar turmas

### ISSUE THREAD

**Issue by Tomahaawk** [BrunoSoares-LABORA/sdd-ufg#93]
![cadastro de turmas](https://cloud.githubusercontent.com/assets/12561157/13050154/b3c2c3dc-d3d8-11e5-8d30-07a488d517c8.png)

**Comment by brunosoaresds** [comment]
Lucas, é necessário atualizar sua base de dados, ela provavelmente está desatualizada. para isto execute os seguintes comandos no "Cake" (Aplicação que você usa para rodar o server):

{...}/cake migrations rollback -t 0
{...}/cake migrations migrate

Vale enfatizar que o repositório ao qual você está utilizando para realizar os testes também deve estar atualizado.

Vou fechar essa issue por estar incorreta, se mesmo após você realizar os procedimentos que recomendei acima este problema estiver ocorrendo você poderá reabri-la.
